import type { AnalysisResponse } from "./replayAnalysisTypes";

export const exampleReplayAnalysis: AnalysisResponse = {
  summary:
    "Sample analysis for a Fox vs Marth match on Battlefield. Use this built-in replay to demo the UI without uploading a .slp file.",
  feedback: [
    "ALPHA#101 won neutral often, but a few openings ended early. Try extending shines or up-throw routes before resetting.",
    "ALPHA#101 missed several tech situations. Tightening defensive reactions would reduce Marth's punish damage.",
    "COACHBOT#777 converted stray hits well and kept stage control, but gave up ledge too often after corner pressure.",
    "Fox vs Marth on Battlefield often comes down to punish consistency. Compare the hit map with the habit cards to spot where conversions stalled.",
  ],
  metadata: {
    num_players: 2,
    stage: "BATTLEFIELD",
    started_at: "2026-03-18T20:42:00Z",
    end_method: "GAME",
    winner_player_index: 0,
    winner_name: "ALPHA#101",
    players: [
      {
        player_index: 0,
        character: "FOX",
        tag: "ALPHA#101",
        connect_code: "ALPHA#101",
        netplay_name: "Alpha",
        name_tag: "ALPHA",
        is_cpu: false,
        stocks_left: 1,
        did_win: true,
      },
      {
        player_index: 1,
        character: "MARTH",
        tag: "COACHBOT#777",
        connect_code: "COACH#777",
        netplay_name: "CoachBot",
        name_tag: "COACH",
        is_cpu: false,
        stocks_left: 0,
        did_win: false,
      },
    ],
  },
  stats: {
    total_frames: 8574,
    total_actions: 1268,
    match_duration_seconds: 143,
    per_player: [
      {
        player_index: 0,
        player_name: "ALPHA#101",
        character: "FOX",
        l_cancel_attempts: 18,
        l_cancel_successes: 13,
        l_cancel_rate: 72.2,
        tech_attempts: 10,
        missed_techs: 4,
        tech_miss_rate: 40,
        tech_towards_count: 3,
        tech_away_count: 2,
        tech_in_place_count: 1,
        actions_per_minute: 315.8,
        ledge_grabs: 7,
        wavedashes: 21,
        wavelands: 12,
        attack_actions: 96,
        movement_actions: 188,
        openings_won: 11,
        kills_secured: 4,
        total_damage_inflicted: 366,
        punishes_faced: 10,
        escaped_punishes: 4,
        openings_per_kill: 2.8,
        damage_per_opening: 33.3,
        neutral_win_rate: 52.4,
        average_opening_length: 2.6,
        attack_ratio: 33.8,
        movement_ratio: 66.2,
      },
      {
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        l_cancel_attempts: 11,
        l_cancel_successes: 7,
        l_cancel_rate: 63.6,
        tech_attempts: 8,
        missed_techs: 2,
        tech_miss_rate: 25,
        tech_towards_count: 2,
        tech_away_count: 3,
        tech_in_place_count: 1,
        actions_per_minute: 254.1,
        ledge_grabs: 10,
        wavedashes: 9,
        wavelands: 8,
        attack_actions: 84,
        movement_actions: 127,
        openings_won: 10,
        kills_secured: 3,
        total_damage_inflicted: 318,
        punishes_faced: 11,
        escaped_punishes: 3,
        openings_per_kill: 3.3,
        damage_per_opening: 31.8,
        neutral_win_rate: 47.6,
        average_opening_length: 2.9,
        attack_ratio: 39.8,
        movement_ratio: 60.2,
      },
    ],
    hit_locations: [
      {
        frame_index: 812,
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        x: -21,
        y: 23,
        damage_taken: 12,
        percent_after_hit: 12,
        is_stock_loss: false,
        launch_dx: 1.8,
        launch_dy: 2.2,
      },
      {
        frame_index: 1164,
        player_index: 0,
        player_name: "ALPHA#101",
        character: "FOX",
        x: 34,
        y: 0,
        damage_taken: 9,
        percent_after_hit: 9,
        is_stock_loss: false,
        launch_dx: -1.4,
        launch_dy: 1.2,
      },
      {
        frame_index: 1702,
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        x: 7,
        y: 48,
        damage_taken: 18,
        percent_after_hit: 44,
        is_stock_loss: false,
        launch_dx: 0.7,
        launch_dy: 2.8,
      },
      {
        frame_index: 2249,
        player_index: 0,
        player_name: "ALPHA#101",
        character: "FOX",
        x: -39,
        y: 25,
        damage_taken: 14,
        percent_after_hit: 38,
        is_stock_loss: false,
        launch_dx: 1.2,
        launch_dy: 2.1,
      },
      {
        frame_index: 2895,
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        x: 42,
        y: 0,
        damage_taken: 15,
        percent_after_hit: 69,
        is_stock_loss: false,
        launch_dx: -2.1,
        launch_dy: 1.5,
      },
      {
        frame_index: 3420,
        player_index: 0,
        player_name: "ALPHA#101",
        character: "FOX",
        x: -14,
        y: 40,
        damage_taken: 11,
        percent_after_hit: 61,
        is_stock_loss: false,
        launch_dx: 0.4,
        launch_dy: 2.6,
      },
      {
        frame_index: 4176,
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        x: -56,
        y: 0,
        damage_taken: 22,
        percent_after_hit: 101,
        is_stock_loss: true,
        launch_dx: -2.9,
        launch_dy: 3.4,
      },
      {
        frame_index: 4892,
        player_index: 0,
        player_name: "ALPHA#101",
        character: "FOX",
        x: 51,
        y: 25,
        damage_taken: 16,
        percent_after_hit: 77,
        is_stock_loss: false,
        launch_dx: -1.7,
        launch_dy: 2.3,
      },
      {
        frame_index: 5628,
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        x: 0,
        y: 0,
        damage_taken: 13,
        percent_after_hit: 28,
        is_stock_loss: false,
        launch_dx: 0,
        launch_dy: 1.8,
      },
      {
        frame_index: 6281,
        player_index: 0,
        player_name: "ALPHA#101",
        character: "FOX",
        x: -28,
        y: 25,
        damage_taken: 19,
        percent_after_hit: 102,
        is_stock_loss: true,
        launch_dx: -2.3,
        launch_dy: 3.1,
      },
      {
        frame_index: 7034,
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        x: 18,
        y: 25,
        damage_taken: 17,
        percent_after_hit: 83,
        is_stock_loss: false,
        launch_dx: 1.3,
        launch_dy: 2.4,
      },
      {
        frame_index: 7922,
        player_index: 1,
        player_name: "COACHBOT#777",
        character: "MARTH",
        x: 61,
        y: 0,
        damage_taken: 24,
        percent_after_hit: 118,
        is_stock_loss: true,
        launch_dx: 3.1,
        launch_dy: 3.8,
      },
    ],
  },
};
