import type { AnalysisResponse } from "../replayAnalysisTypes";

export const exampleReplayAnalysis: AnalysisResponse = {
  stats: {
    total_frames: 14268,
    total_actions: 655,
    match_duration_seconds: 237.8,
    hit_locations: [
      {
        frame_index: 560,
        player_index: 0,
        player_name: "NEBULA",
        character: "FOX",
        x: -42,
        y: 9,
        damage_taken: 8,
        percent_after_hit: 17,
        is_stock_loss: false,
        launch_dx: 1.5,
        launch_dy: 0.9,
      },
      {
        frame_index: 1380,
        player_index: 1,
        player_name: "SPARK",
        character: "FALCO",
        x: 33,
        y: 2,
        damage_taken: 12,
        percent_after_hit: 29,
        is_stock_loss: false,
        launch_dx: -1.2,
        launch_dy: 1.1,
      },
      {
        frame_index: 2470,
        player_index: 0,
        player_name: "NEBULA",
        character: "FOX",
        x: -6,
        y: 26,
        damage_taken: 15,
        percent_after_hit: 66,
        is_stock_loss: false,
        launch_dx: 0.8,
        launch_dy: 1.7,
      },
      {
        frame_index: 3190,
        player_index: 1,
        player_name: "SPARK",
        character: "FALCO",
        x: 12,
        y: 31,
        damage_taken: 18,
        percent_after_hit: 77,
        is_stock_loss: false,
        launch_dx: -0.6,
        launch_dy: 1.9,
      },
      {
        frame_index: 4985,
        player_index: 0,
        player_name: "NEBULA",
        character: "FOX",
        x: 58,
        y: 16,
        damage_taken: 20,
        percent_after_hit: 98,
        is_stock_loss: true,
        launch_dx: 2.3,
        launch_dy: 1.5,
      },
      {
        frame_index: 7160,
        player_index: 1,
        player_name: "SPARK",
        character: "FALCO",
        x: -29,
        y: 12,
        damage_taken: 14,
        percent_after_hit: 63,
        is_stock_loss: false,
        launch_dx: 1.1,
        launch_dy: 0.4,
      },
      {
        frame_index: 9050,
        player_index: 1,
        player_name: "SPARK",
        character: "FALCO",
        x: -41,
        y: 18,
        damage_taken: 23,
        percent_after_hit: 111,
        is_stock_loss: true,
        launch_dx: -2.1,
        launch_dy: 2.2,
      },
      {
        frame_index: 11820,
        player_index: 0,
        player_name: "NEBULA",
        character: "FOX",
        x: 14,
        y: 7,
        damage_taken: 9,
        percent_after_hit: 34,
        is_stock_loss: false,
        launch_dx: 0.9,
        launch_dy: 0.5,
      },
      {
        frame_index: 13640,
        player_index: 0,
        player_name: "NEBULA",
        character: "FOX",
        x: -53,
        y: 23,
        damage_taken: 26,
        percent_after_hit: 124,
        is_stock_loss: true,
        launch_dx: -2.5,
        launch_dy: 2.4,
      },
    ],
    per_player: [
      {
        player_index: 0,
        player_name: "NEBULA",
        character: "FOX",
        l_cancel_attempts: 28,
        l_cancel_successes: 22,
        l_cancel_rate: 78.6,
        tech_attempts: 9,
        missed_techs: 3,
        tech_miss_rate: 33.3,
        tech_towards_count: 3,
        tech_away_count: 2,
        tech_in_place_count: 1,
        actions_per_minute: 164.3,
        ledge_grabs: 4,
        wavedashes: 14,
        wavelands: 8,
        attack_actions: 188,
        movement_actions: 331,
        openings_won: 16,
        kills_secured: 2,
        total_damage_inflicted: 281,
        punishes_faced: 14,
        escaped_punishes: 6,
        openings_per_kill: 8,
        damage_per_opening: 17.6,
        neutral_win_rate: 53.3,
        average_opening_length: 2.6,
        attack_ratio: 36.3,
        movement_ratio: 63.7,
      },
      {
        player_index: 1,
        player_name: "SPARK",
        character: "FALCO",
        l_cancel_attempts: 31,
        l_cancel_successes: 27,
        l_cancel_rate: 87.1,
        tech_attempts: 11,
        missed_techs: 2,
        tech_miss_rate: 18.2,
        tech_towards_count: 2,
        tech_away_count: 4,
        tech_in_place_count: 3,
        actions_per_minute: 158.2,
        ledge_grabs: 6,
        wavedashes: 11,
        wavelands: 6,
        attack_actions: 201,
        movement_actions: 312,
        openings_won: 14,
        kills_secured: 3,
        total_damage_inflicted: 304,
        punishes_faced: 16,
        escaped_punishes: 5,
        openings_per_kill: 4.7,
        damage_per_opening: 21.7,
        neutral_win_rate: 46.7,
        average_opening_length: 2.9,
        attack_ratio: 39.2,
        movement_ratio: 60.8,
      },
    ],
  },
  feedback: [
    "NEBULA: Your neutral wins were solid, but missed techs led directly to extended Falco pillar strings. Tighten your defensive reactions after first hit.",
    "NEBULA: You converted dash-dance whiff punishes well. Look for earlier kill confirms off up-smash before opponent reaches high percent.",
    "SPARK: Your pressure maintained tempo effectively, especially after cornering Fox. Continue mixing late aerial timings to force shield mistakes.",
    "SPARK: A few recoveries drifted predictably toward stage. Add more variation in side-B height and double-jump timing.",
  ],
  summary:
    "A fast-paced Battlefield set where Falco edged out the win through stronger punish conversion, while Fox found success in neutral but missed a few key survivability moments.",
  metadata: {
    players: [
      {
        player_index: 0,
        character: "FOX",
        tag: "NEBULA",
        connect_code: "NEB#101",
        netplay_name: "Neb",
        name_tag: "",
        is_cpu: false,
        stocks_left: 0,
        did_win: false,
      },
      {
        player_index: 1,
        character: "FALCO",
        tag: "SPARK",
        connect_code: "SPK#404",
        netplay_name: "Spark",
        name_tag: "",
        is_cpu: false,
        stocks_left: 1,
        did_win: true,
      },
    ],
    num_players: 2,
    stage: "BATTLEFIELD",
    started_at: "2025-01-16T22:17:03Z",
    end_method: "GAME",
    lras_initiator: null,
    winner_player_index: 1,
    winner_name: "SPARK",
  },
};
